"""Experiment settings shared by every module of the demo."""

from pathlib import Path

import numpy as np

SHIFT = np.pi / 2  # parameter-shift offset for gates generated by Pauli/2
SHOT_COUNTS = (100, 1000, 10000)
REPETITIONS = 500  # independent gradient estimates per shot count
LEARNING_RATE = 0.1  # η in the example optimizer step
SEED = 42

FIGURE_DIR = Path(__file__).parent / "figures"
FIGURE_DPI = 150
